# Generated by Django 5.2.6 on 2025-11-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_mymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
    ]
