# Generated by Django 5.2.6 on 2025-11-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_review_owner'),
        ('users', '0005_message_body_message_created_message_is_read_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
